[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
edition     = "2021"
license     = "MIT"
name        = "swc-vanilla-extract-visitor"
repository  = "https://github.com/kwonoj/swc-plugin-vanilla-extract"
version     = "0.0.1"

[dependencies]
once_cell = "1.14.0"
swc_core = "0.22.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
