[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Vanilla-extract custom transform visitor for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-vanilla-extract-visitor"
repository  = "https://github.com/kwonoj/swc-plugin-vanilla-extract"
version     = "0.0.2"

[dependencies]
once_cell = "1.16.0"
regex          = "1.7.0"
path-slash = "0.2.1"
swc_core                = { version = "0.75.11", features = ["common", "ecma_quote", "ecma_ast", "ecma_visit", "ecma_visit_path"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
