[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Vanilla-extract plugin for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-vanilla-extract"
repository  = "https://github.com/kwonoj/swc-plugin-vanilla-extract"
version     = "0.0.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"
swc-vanilla-extract-visitor = { path = "../swc-vanilla-extract-visitor", version = "0.0.2" }
swc_core                = { version = "0.75.11", features = ["ecma_plugin_transform", "ecma_visit_path"] }
