[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-vanilla-extract"
repository  = "https://github.com/kwonoj/swc-plugin-vanilla-extract"
version     = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc-vanilla-extract-visitor = { path = "../swc-vanilla-extract-visitor", version = "0.0.1" }
swc_core                = { version = "0.22.0", features = ["plugin_transform", "ecma_visit_path"] }